### ISSUE TITLE
Clean up introduction of "RTP over QUIC" and "RoQ" terms in the draft

### ISSUE THREAD

**Issue by SpencerDawkins** [mengelbart/rtp-over-quic-draft#107]
ISTM that "RTP over QUIC" and "RoQ" should appear in the Abstract and Introduction, but neither does, and we don't actually say that we're going to be referring to "RTP over QUIC" as "RoQ" in the document.

**Comment by mengelbart** [comment]
We have the following in the introduction:

> The mapping described in this document is called RTP over QUIC (RoQ).

But adding it to the abstract might be good, too.
