### ISSUE TITLE
Guidance on RoQ DATAGRAM use

### ISSUE THREAD

**Issue by SpencerDawkins** [mengelbart/rtp-over-quic-draft#114]
@SpencerDawkins and @mengelbart sait through some really interesting discussion at WEBTRAN about pooled connections ...

**Comment by SpencerDawkins** [comment]
The slides for that discussion are [here](https://datatracker.ietf.org/meeting/117/materials/slides-117-webtrans-ietf-117-webtrans-wg-slides-02), starting with slide 9.

**Comment by SpencerDawkins** [comment]
From discussion at IETF 114

> Spencer Dawkins: Would it be useful to give guidance on using streams vs datagrams? Or even switching from streams to datagrams after STOP_SENDING on a stream?
> Bernard Aboba: Sending video over streams and audio over datagrams, for example, makes sense. However, switching doesn't make sense.
> What should a receiver do if it receives a video frame over a QUIC stream, and packets from the same frame over datagrams?
> Spencer (echoing Bernard): maybe the guidance should include "pick either streams or datagrams for a media flow, but don't plan on doing both, or switching between them"
> Mo: MoQ is doing something similar here, and decided to allow senders to decide how to deliver media over streams or datagrams, not constrained by receiver preferences. But that may reflect MoQ almost always doing fan-out to many receivers, and we're probably talking about 1:1 here. But Mo agrees with Bernard that both streams and datagrams are useful.
> Peter Thatcher: Another use case is FEC over datagrams for media over datagrams, with reliable media sent over streams. Agree this should be a sender optimization not dictated by receivers.

**Comment by SpencerDawkins** [comment]
From discussion at IETF 118

> For a given media stream, choose either streams or datagrams, don’t switch
> Allow senders to optimize, e.g., audio/datagrams and video/streams or even I-frames/streams and P-/B-frames/datagrams, FEC use cases

These are somewhat contradictory. :stuck_out_tongue:

On balance, we should allow senders to make the right decision about what is carried in streams, what is carried in datagrams, and how RTP streams are switched between QUIC streams and QUIC DATAGRAMs.

**Comment by SpencerDawkins** [comment]
@SpencerDawkins will review [Section 3.1](https://datatracker.ietf.org/doc/html/draft-ietf-avtcore-rtp-over-quic#name-rtp-with-quic-streams-quic-) and see whether we can/need to say anything else.

**Comment by SpencerDawkins** [comment]
> @SpencerDawkins will review [Section 3.1](https://datatracker.ietf.org/doc/html/draft-ietf-avtcore-rtp-over-quic#name-rtp-with-quic-streams-quic-) and see whether we can/need to say anything else.

Having reviewed [Section 3 in the current main branch](https://mengelbart.github.io/rtp-over-quic-draft/draft-ietf-avtcore-rtp-over-quic.html#name-rtp-with-quic-streams-quic-), I think Section 3.1 says a lot about streams and datagrams, so adding a lot more material there probably isn't the right thing to do, but we've talked about a lot of considerations in this issue (and in the meeting discussions that we mentioned in comments), that probably ought to be included somewhere else. I suggest adding a guidance section as part of [Section 5](https://mengelbart.github.io/rtp-over-quic-draft/draft-ietf-avtcore-rtp-over-quic.html#name-encapsulation) or [Section 7](https://mengelbart.github.io/rtp-over-quic-draft/draft-ietf-avtcore-rtp-over-quic.html#name-congestion-control-and-rate). 

I'll start on a PR, and try to do the right thing, but am obviously interested in feedback.

**Comment by aboba** [comment]
@SpencerDawkins Aside from transport of media, there is also the question of whether RTCP should be sent over datagrams, streams or both.
