### ISSUE TITLE
Reasoning for not mandating a rate adaptation algorithm

### ISSUE THREAD

**Issue by gchandok** [mengelbart/rtp-over-quic-draft#116]
A rate adaptation algorithm can be plugged in to adapt the media
    bitrate to the available bandwidth.  This document does not mandate
|   any specific rate adaptation algorithm, _because the desired response
|   to congestion can be application and codec-specific.  For example,
|   adjusting quantization in response to congestion may work well in
|   many cases, but if what's being shared is video that includes text,
|   maintaining readability is important._
|
|   As of this writing, the IETF has produced two Experimental-track rate
|   adaptation specifications, Network-Assisted Dynamic Adaptation (NADA)
|   [RFC8698] and Self-Clocked Rate Adaptation for Multimedia (SCReAM)
|   [RFC8298]. 

**Rate adaptation mechanisms like NADA/SCREAM don’t necessarily mandate how the encoder handles the rate changes. That handling may be codec specific so makes sense to leave it out. So the argument and example (in italics) don’t seem appropriate in this section. Rate adaptation mechanism RFCs you mention above talk about how the sending rate should be computed, what feedback is needed and how traffic should be paced / shaped which are not codec specific. You can just say that application may pick a rate adaptation mechanism of its choice and this document does not mandate it. That should be sufficient**

**Comment by SpencerDawkins** [comment]
@gchandok - let me take a look at this. I think it's useful to say something about why we wouldn't mandate ANY rate adaptation algorithm, but if I can't come up with better text, I agree that confusing text as currently isn't useful ...

**Comment by SpencerDawkins** [comment]
@gchandok - I've now taken a look at this, and I think our problem is that I am conflating two things that need to be described separately - the response that an application takes to adjust the encoded media stream it sends, and the mechanism that an application uses to decide how to send it. I think both of these are important to mention, but they are two different things, and need to be explained in a way that clearly distinguishes between them. 

I'm working on a PR for this ...
