### ISSUE TITLE
Carrying SR NTP Timestamps at QUIC layer

### ISSUE THREAD

**Issue by gchandok** [mengelbart/rtp-over-quic-draft#118]
_SR_ NTP timestamps: We cannot send NTP timestamps in the same
      format the SRs use, but couldn't a QUIC timestamp extension
      provide the same information?

**SR really carries an RTP timestamp to NTP time mapping that is required for lip sync. This cannot solely be provided at the QUIC layer since it does not know about RTP timestamps**

**Comment by SpencerDawkins** [comment]
We think the action here is to remove the editor's note and clarify that QUIC signaling can't replace this, even with a timestamp extension.
