### ISSUE TITLE
Define how RoQ reacts to the absence of max_datagram_frame_size transport parameter

### ISSUE THREAD

**Issue by SpencerDawkins** [mengelbart/rtp-over-quic-draft#122]
While working on a PR for Issue #93 I noticed the following text in [Section 3 of RFC 9221](https://datatracker.ietf.org/doc/html/rfc9221#name-transport-parameter):

> Application protocols that use datagrams **MUST** define how they react to the absence of the max_datagram_frame_size transport parameter. If datagram support is integral to the application, the application protocol can fail the handshake if the max_datagram_frame_size transport parameter is not present.

I don't think this belongs in a subsection of [Section 3 in the RoQ draft](https://mengelbart.github.io/rtp-over-quic-draft/draft-ietf-avtcore-rtp-over-quic.html#name-protocol-overview), but we do need to do it, and we should talk about what the behavior should be before we add this to the draft (probably in [Section 4 of the ROQ draft](https://mengelbart.github.io/rtp-over-quic-draft/draft-ietf-avtcore-rtp-over-quic.html#name-connection-establishment-an).

**Comment by SpencerDawkins** [comment]
Related to #13

**Comment by SpencerDawkins** [comment]
We note that the description of the decisions a RoQ receiver must make goes in [Section 3 in the RoQ draft](https://mengelbart.github.io/rtp-over-quic-draft/draft-ietf-avtcore-rtp-over-quic.html#name-protocol-overview), but the errors if datagrams are signaled but not negotiated goes in [Section 4 of the ROQ draft](https://mengelbart.github.io/rtp-over-quic-draft/draft-ietf-avtcore-rtp-over-quic.html#name-connection-establishment-an)

**Comment by mengelbart** [comment]
This is actually already explained in [section 5.3](https://mengelbart.github.io/rtp-over-quic-draft/draft-ietf-avtcore-rtp-over-quic.html#section-5.3). We could also add it to the connection establishment section, although I'm not sure if that is really necessary. I don't think we need to add this detail to the protocol overview in section 3.

**Comment by SpencerDawkins** [comment]
@SpencerDawkins notes that this is close enough to #13 that it could have been a duplicate. Even if it's not a duplicate, we can probably close both with one PR.

**Comment by SpencerDawkins** [comment]
@SpencerDawkins notes that he has apparently gotten lost on the original point for this (non- #13) point:

> **Application protocols that use datagrams MUST define how they react** to the absence of the max_datagram_frame_size transport parameter. If datagram support is integral to the application, the application protocol can fail the handshake if the max_datagram_frame_size transport parameter is not present.

That is to say, it would be helpful to 

- point out that you can "hope" to use datagrams,
- and even offer/answer that you want to use datagrams, 
- but if you don't negotiate the use of datagrams in the QUIC handshake, you've got some choices to make. 

I'll work on a PR for **that**.
