### ISSUE TITLE
Normative References

### ISSUE THREAD

**Issue by aboba** [mengelbart/rtp-over-quic-draft#127]
From the AVTCORE WG mailing list: https://mailarchive.ietf.org/arch/msg/avt/WH8OTXO7LT8IQzxPh2QwfeGVcF0/

With the QUIC specifications still evolving, this specification is put in a difficult position.  Beyond the basic QUIC specifications, there are extensions which could be of potential benefit.  However, some of the extensions are not yet WG work items, or are not widely deployed, or may take some time to be published as RFCs, or may never be published as RFCs.

Currently, the document has an Appendix A: List of Optional QUIC extensions, which states "The following is a list of QUIC protocol extensions that might be beneficial for RoQ, but are not required by RoQ." Putting discussion of non-RFC QUIC extensions into a (non-normative) Appendix seems like a good idea, if it could allow the main specification to focus on the core QUIC functionality and avoid normative references to documents which may or may not ever be published as RFCs.

However, the problem is that discussion of the extensions is not limited to the (non-normative) Appendix, but is contained in other sections, including Sections 7, 7.3.4 and 8.1.

This results in normative references to [I-D.draft-huitema-quic-ts], [I-D.draft-ietf-quic-ack-frequency] and [I-D.draft-smith-quic-receive-ts]. ¶

I would like to suggest that the RTP over QUIC specification be restructured so as to only normatively reference documents which have been published as RFCs.

For this to work, material in Sections 6, 7 and 8 may need to be moved to Appendix A, which would presumably avoid normative references.

**Comment by SpencerDawkins** [comment]
@aboba - I have what I hope is a friendly amendment to this proposal:

> I would like to suggest that the RTP over QUIC specification be restructured so as to only normatively reference documents which have been published as RFCs.

I don't think limiting ourselves to published RFCs is quite right, but it's a step in the right direction. 

I think moving helpful commentary about things that might be done into appendices is a step in the right direction. This would include the observations we make about timestamps, etc. 

I think we might have exceptions to "only published RFCs" for drafts that are 

- adopted by QUIC or a similar WG, or 
- adopted and considered mature enough to wait for, or
- past WGLC and somewhere in the publication requested/approved state machine. 

Does that make sense?

Assuming so, Mathis will propose a linked PR that moves what we think needs to be moved into appendices, and we'll talk, OK?
