### ISSUE TITLE
Congestion and rate control in motivation section

### ISSUE THREAD

**Issue by mengelbart** [mengelbart/rtp-over-quic-draft#135]
From @aboba in https://github.com/mengelbart/rtp-over-quic-draft/issues/128:

> 
> Looking over the coverage of Congestion Control and Rate Control, the two
> topics appear to be conflated in places and also there appear to be some issues that
> have not been fully considered.
> 
> Section 1.2.2
> 
> While the effect of QUIC's response to congestion means that some RTP
> packets will arrive at the receiver later than a user of the RTP flow might
> prefer, it is still preferable to "ceasing transmission" completely until
> the RTP sender has a reason to believe that restarting the flow will not
> result in congestion.¶
> 
> [BA] In contrast to circuit breakers, which do not restrict the ability to
> send RTCP feedback, QUIC congestion control affects RTCP feedback, not just
> RTP. So saying QUIC congestion control is "preferable" seems questionable.
> 
> Moreover, when a single QUIC connection is used to multiplex both RTP-RTCP
> and non-RTP packets as described in Section 1.2.5
> the QUIC connection will still be Internet-safe, with no coordination
> required.
> 
> [BA] While it may be "Internet-safe", delays in RTCP feedback are likely to
> destabilize rate control as well as resulting in challenges to A/V sync.
> So not sure that "Internet-safe" is the only important metric here.
> 
> Section 1.2.3
> 
> One word of caution is in order - RTP implementations may rely on at least
> some minimal periodic RTCP feedback, in order to determine that an RTP flow
> is still active, and is not causing sustained congestion (as described in
> RFC8083, but since this "periodicity" is measured in seconds, the impact of this "duplicate"
> feedback on path bandwidth utilization is likely close to zero.
> 
> [BA] Under congestion, RTCP feedback can potentially be delayed
> substantially. Here the issue is not "bandwidth utilization" but whether
> RTCP receives the transport treatment required for control traffic. Note
> also that similar considerations apply to treatment of audio vs. video.
> Serious problems with a/v sync are possible (or even likely) under
> congestion.

**Comment by SpencerDawkins** [comment]
@SpencerDawkins notes that the subtle definitions of congestion control and rate adaptation have morphed in the decades since Van Jacobson introduced slow start, congestion avoidance, etc. One of the most obvious differences is that even the mechanisms that focus on "defending the network" are now likely to include some form of "chirping", to avoid bufferbloat, etc. 

It would be useful to actually point this out in the RoQ document, point to the definitions we have included in the terminology section, and say that guessing what we mean without looking at the definitions will probably be confusing at best.

**Comment by SpencerDawkins** [comment]
@aboba, thank you for the pushback. I wrote much of the text you are commenting on, and I appreciate feedback representing the endpoint's point of view, and not just the network's point of view. 

I'm working on a PR for this now. I'll ask you to look it over, when it's in the repo.
