### ISSUE TITLE
Does RTP over datagram retransmission happen on the same flow ID?

### ISSUE THREAD

**Issue by LPardue** [mengelbart/rtp-over-quic-draft#16]
See https://www.ietf.org/archive/id/draft-engelbart-rtp-over-quic-04.html#section-6.2

It would seem to be sensible to recommend retransmitting the RTP packet on the same datagram flow ID but I'm not an expert on RTP stuff.

**Comment by mengelbart** [comment]
I think it would depend on how the RTP implementation is doing retransmissions. RFC 4588 allows retransmissions either in the same session with a different SSRC or in a separate session. If different flow IDs are required for different sessions, as is the case in the current draft, then that would also be the case for retransmissions in different sessions, but not for retransmissions that happen in the same session.

**Comment by LPardue** [comment]
That sounds reasonable. Since it sounds like there are some implementation decisions to make, It might be helpful to note that this type of retransmission behaviour is possible, and what the implications are for both stream-based or datagram-based retransmissions.
