### ISSUE TITLE
Adding descriptions of experiments and future work for publication as Experimental 

### ISSUE THREAD

**Issue by SpencerDawkins** [mengelbart/rtp-over-quic-draft#161]
@aboba suggested that we add this issue, at the [interim-2024-avtcore-01](https://datatracker.ietf.org/meeting/interim-2024-avtcore-01/session/avtcore) meeting, Various points described here might end up in the shepherd write-up, a "future work" section in the document, or both. 

Better understanding of useful guidelines and recommendations for congestion control and rate adaptation for multiple RoQ flows (whether streams or datagrams). 

Guidance for using RoQ over QUIC multipath. 

Coexistence between RoQ on its own ALPN and QUIC over ICE, if the QUIC working group produces a "QUIC with ICE" specification. 

Stable reference for implementers to interop test with, and report results.

**Comment by aboba** [comment]
This s a good start.  A few others to consider: 

* Transport for RTCP (e.g. QUIC streams vs. datagrams)
* Role of QUIC extensions (e.g. to estimate one-way transit)
* Realtime-friendly congestion control algorithms (COPA, L4S, etc.)

**Comment by SpencerDawkins** [comment]
@aboba - thanks for the additions. 

I think we are talking about two different things, but they both need to be in the document:

- Topics that we need QUIC extensions to address, or address well, and 
- Topics that we need implementation experience with in order to address, or address well. 

The first category would be directions for future work on RoQ in AVTCORE.
The second category would be "why this document is published as experimental"

Does that make sense?
