### ISSUE TITLE
Questions about section 1.3

### ISSUE THREAD

**Issue by mengelbart** [mengelbart/rtp-over-quic-draft#168]
> This specification focuses on providing a secure encapsulation of RTP packets for transmission over QUIC. The expected usage is wherever RTP is used to carry media packets, allowing QUIC in place of other transport protocols such as TCP, UDP, SCTP, DTLS, etc. That is, we expect RoQ to be used in contexts in which a signaling protocol is used to announce or negotiate a media encapsulation and the associated transport parameters (such as IP address, port number). RoQ is not intended as a stand-alone media transport, although QUIC transport parameters could be statically configured.

Reviewing this paragraph I have some questions:
1. Is SCTP actually used to carry RTP? If not, should we remove the reference here to avoid confusion?
2. What does it mean that _QUIC transport parameters could be statically configured_? I don't think that makes sense. Did we mean to say RTP parameters could be statically configured (instead of using explicit signaling)?

**Comment by SpencerDawkins** [comment]
> > This specification focuses on providing a secure encapsulation of RTP packets for transmission over QUIC. The expected usage is wherever RTP is used to carry media packets, allowing QUIC in place of other transport protocols such as TCP, UDP, SCTP, DTLS, etc. That is, we expect RoQ to be used in contexts in which a signaling protocol is used to announce or negotiate a media encapsulation and the associated transport parameters (such as IP address, port number). RoQ is not intended as a stand-alone media transport, although QUIC transport parameters could be statically configured.
> 
> Reviewing this paragraph I have some questions:
> 
> 1. Is SCTP actually used to carry RTP? If not, should we remove the reference here to avoid confusion?

Well, yes, for some value of **"actually"** - at least, [the relevant IANA registry](https://www.iana.org/assignments/sdp-parameters/sdp-parameters.xhtml#sdp-parameters-2) has these entries: 

- proto	UDP/DTLS/SCTP	[[RFC8841](https://www.iana.org/go/rfc8841)]
- proto	TCP/DTLS/SCTP	[[RFC8841](https://www.iana.org/go/rfc8841)]

> 2. What does it mean that _QUIC transport parameters could be statically configured_? I don't think that makes sense. Did we mean to say RTP parameters could be statically configured (instead of using explicit signaling)?

That wouldn't surprise me - but I think this was written when we were wandering in the weeds, between "not needing to use an ALPB to set up a RoQ QUIC connection" and "not needing to  use SDP to set up a RoQ RTP connection". The bigger question is whether we need to say anything about EITHER of these things - we're certainly not encouraging implementers to try to do RoQ that way.
