### ISSUE TITLE
P2P and Client/Server connection setup

### ISSUE THREAD

**Issue by mengelbart** [mengelbart/rtp-over-quic-draft#194]
I am also noticing 

> The above implies that **RoQ is targeted at peer-to-peer operation**; but it may also be used in client-server-style settings, e.g., when talking to a conference server as described in RFC 7667 ([[RFC7667](https://mengelbart.github.io/rtp-over-quic-draft/draft-ietf-avtcore-rtp-over-quic.html#RFC7667)]), or, if RoQ is used to replace RTSP ([[RFC7826](https://mengelbart.github.io/rtp-over-quic-draft/draft-ietf-avtcore-rtp-over-quic.html#RFC7826)]), to a media server.

I THINK the point is "peer to peer will work fine if you set up QUIC connections directly to the right places, and this document doesn't describe how that happens, and that description should be in some other document", but I should probably say that clearly.

_Originally posted by @SpencerDawkins in https://github.com/mengelbart/rtp-over-quic-draft/issues/163#issuecomment-2047826581_

**Comment by SpencerDawkins** [comment]
#195 is a general cleanup of "peer" and "endpoint", and won't change 

> The above implies that RoQ is targeted at **peer-to-peer** RTP operation; but it can also be used in RTP client-server-style settings, e.g., when talking to a conference server as described in RFC 7667 ([RFC7667]), or, if RoQ is used to replace RTSP ([RFC7826]), to a media server.

That's left for this issue.

**Comment by SpencerDawkins** [comment]
The more I look at this issue, and the surrounding text that it describes, the more I suspect that (because we're talking about media streams) what we should say is mostly about RTP. My apologies for being confused!
