### ISSUE TITLE
Section 8: Bandwidth sharing

### ISSUE THREAD

**Issue by aboba** [mengelbart/rtp-over-quic-draft#20]
"*TODO:* Add considerations for bandwidth shares when a QUIC connection is shared between RTP and non-RTP streams?"

**Comment by mengelbart** [comment]
This was done by adding [section 8.3](https://www.ietf.org/archive/id/draft-ietf-avtcore-rtp-over-quic-00.html#name-shared-quic-connections) but I forgot to remove the TODO. I will create a PR.
