### ISSUE TITLE
Resolve Signaling dependency discussed in interim meeting

### ISSUE THREAD

**Issue by mengelbart** [mengelbart/rtp-over-quic-draft#223]
At the last interim meeting, we discussed the changes made in #212. Some points that came up in the discussion:

- The sentence *MUST be negotiated using appropriate signaling* creates a dependency on signaling that should not exist.
- We should allow endpoints to close the connection with error code unknown flow IDs.
- Ideally, signaling should finish before packets carrying flow IDs that depend on the signaling are sent.
- Buffering *some* amount of data arriving with unknown flow IDs is a reasonable solution if necessary because signaling can't be guaranteed to finish in time, and applications can deal with the buffered data.

**Comment by SpencerDawkins** [comment]
> * The sentence _MUST be negotiated using appropriate signaling_ creates a dependency on signaling that should not exist.

I agree on this point, but we should be more explicit in the draft - at least some people intend to use RoQ without signaling (whether via preconfiguration, or just endpoints figuring out what to do with unknown flow IDs).
