### ISSUE TITLE
Section 6: Multiplexing of non-RTP/RTCP data streams and datagrams

### ISSUE THREAD

**Issue by aboba** [mengelbart/rtp-over-quic-draft#24]
"  For multiplexing different RTP and other data streams on the same
   QUIC connection, each RTP/RTCP packet is prefixed with a flow
   identifier.  A flow identifier is a QUIC variable-length integer
   which must be unique per stream...

   Differentiating RTP/RTCP packets of different RTP sessions from non-
   RTP/RTCP datagrams is the responsibility of the application by means
   of appropriate use of flow identifiers and the corresponding
   signaling."

[BA] This text is a bit vague with respect to setup of non-RTP/RTCP data streams and datagrams.

As an example, in WebRTC it is possible to [create additional data channels without signaling](https://w3c.github.io/webrtc-pc/#rtcdatachannel). 

How would equivalent functionality be supported in RTP over QUIC? For example, one might assume that the desire to exchange data is negotiated, but once done, that a non-RTP/RTCP data stream or datagrams could then be received.  How are these non-RTP/RTCP data streams or datagrams distinguished from RTP/RTCP?  Do we examine the first octet as per RFC 7983bis or is some other multiplexing mechanism used?

**Comment by mengelbart** [comment]
Initially, the idea was to require the flow identifier in every datagram sent on the QUIC connection, allowing the receiver to demultiplex based on the flow identifier. However, that may require some signaling to map flow identifiers to protocols, and as you rightly point out, it may be desired to open new channels without additional signaling, and the flow identifier could also conflict with other protocol mappings to QUIC streams/datagrams.

I think this is also related to #31. Depending on what ALPN we define in this document and which combinations of protocols this ALPN includes, we may have different multiplexing requirements.

The easiest case would probably be an ALPN like "rtp-quic" that identifies RTP over QUIC without multiplexing additional non-RTP/RTCP protocols. In that case, we could rely on traditional multiplexing mechanisms for RTP/RTCP, such as RFC 5761 for multiplexing RTP and RTCP or RFC 8860 for sending multiple types of media in a single RTP session. However, I think both RFCs have some limitations that a flow identifier could potentially solve at the cost of some bytes.

Multiplexing RTP/RTCP and other protocols will be more complicated. One solution could be RFC 7983bis. RFC 7983bis may not work if RTP/RTCP packets are prepended with a flow identifier, which may be solved by prepending the flow identifier with another byte that takes a value that does not yet match any other protocol in RFC 7983bis. But I am not sure if RFC 7983bis is what we need here, given that something like data channels could run directly in QUIC and would not necessarily need to be encapsulated in SCTP/DTLS over QUIC.

If we leave multiplexing of multiple protocols to future documents with a separate ALPN in #31, we could also leave the specifics of how the multiplexing works to those documents. In that case, it might be valuable to add a *Multiplexing Guidelines* section to this document.

**Comment by mengelbart** [comment]
Resolved in #54
