### ISSUE TITLE
Section 6.1: RTP topologies

### ISSUE THREAD

**Issue by aboba** [mengelbart/rtp-over-quic-draft#25]
*Editor's Note:* Note, however, that using a single frame per
      stream in a single RTP packet may cause interworking issues when a
      translator wants to forward packets received via RTP-over-QUIC to
      an endpoint as UDP packets because the received ADUs may exceed
      the MTU size or even maximum UDP packet size.

[BA] This (and other aspects, such as lack of multicast support) has implications for the [supportable RTP topologies](https://datatracker.ietf.org/doc/html/rfc7667). There is also the issue of RTCP interworking. Are there specific topologies that are not supported for use with RTP over QUIC?

**Comment by mengelbart** [comment]
The introduction currently limits RTP over QUIC to unicast topologies:

> The scope of this document is limited to unicast RTP/RTCP.

We may need to re-evaluate multicast topologies if [QUIC multicast](https://datatracker.ietf.org/doc/draft-jholland-quic-multicast/) becomes available.

I think most of the non-multicast topologies should be supportable with a few constraints. Whenever a middlebox like a translator needs access to the RTP packet, the QUIC connection must be terminated at the middlebox. I think RTP over QUIC can also support the case described in the note if the translator can rewrite the RTP packets to smaller ones.

Should we add a new section to explain these limitations?

**Comment by aboba** [comment]
Adding a section to explain the limitations would make sense. 

Having a middlebox packetizing frames is complex, because RTP packetization is codec-specific.  Some MANEs do this today (e.g. in order to adjust to MTU differences), but typically those MANEs only support a single codec.
