### ISSUE TITLE
ALPN for sharing a connection between RTP/RTCP and other protocols

### ISSUE THREAD

**Issue by mengelbart** [mengelbart/rtp-over-quic-draft#31]
One of the advantages of RTP over QUIC is the possibility to multiplex different protocols on the same connection. A simple use case for this is to share a single QUIC connection between a media session using RTP and some non-RTP data transfer, similar to WebRTC Data Channels. *draft-ietf-avtcore-rtp-over-quic* specifies a minimal application usage of QUIC for RTP. The draft defines an ALPN token (“rtp-mux-quic”) because QUIC requires the usage of a mechanism to agree on an application layer protocol, and ALPN is the currently specified way of doing this using TLS. Other application usages of QUIC will have to define their own ALPN token, which implies that they must use a different QUIC connection from RTP over QUIC.

We currently see two possible ways to allow usage of RTP and other protocols multiplexed on the same QUIC connection:

* Define a generic ALPN (e.g. “rtp-mux-sdp”), which indicates that the application protocols to be carried in this connection are to be negotiated out of band (SDP). The problem with this approach is that we cannot define the actual multiplexing of the two protocols.
* Explicitly state in the RTP over QUIC draft that future documents are allowed to define new ALPNs that identify protocols for multiplexing RTP over QUIC with other protocols. For example, an ALPN “rtp-mux-h3” could be defined in a document that defines how RTP and HTTP/3 can be multiplexed in one QUIC connection. This document could reference the RTP over QUIC document but would have to explain how to multiplex the different protocols.

Of course, these two options are not mutually exclusive.

**Comment by aboba** [comment]
For an example of how this can be handled, see [RFC 8833](https://www.rfc-editor.org/rfc/rfc8833.html), which defines the ALPN registration for WebRTC.  The document defines two ALPNs, each of which supports multiplexing of both data and media. At no point does the document mention SDP. Looking at that document, something simple like "rtp-mux-quic" might be fine.

Multiplexing of RTP-over-QUIC and HTTP/3 would be quite a complex exercise, because this would pull in interactions with HTTP/3 pooling, where multiple applications can interact.  As you've noted, RTP-over-QUIC has unique congestion control requirements which QUIC implementations used with HTTP/3 might not comply with (e.g. BBRv1).

**Comment by mengelbart** [comment]
I think RFC 8833 would be an example of the second option, where a separate document defines an ALPN for multiplexing two protocols. I agree HTTP/3 might be very complex and there are better examples that may be easier to define and possibly more useful. I assume we still need an ALPN in the RTP over QUIC document (e.g., "rtp-quic"), that can be used to exclusively send RTP and some other document could define an ALPN "rtp-mux-quic", for multiplexing RTP and something like data channels.

**Comment by aboba** [comment]
Not sure you'd need multiple ALPNs here. As an example, applications using WebTransport do not need a separate ALPN for each use case.  Similarly, WebRTC was able to use a single ALPN for both data and media by leveraging RFC 7983.

**Comment by mengelbart** [comment]
I think leveraging RFC 7983bis could work, but I am not sure it is what we need. WebRTC uses DTLS/SCTP for data, both of which *I think* we do not need on top of QUIC. But that leaves the question of what protocol will be used on top of QUIC to carry data instead. That's why I thought we could just define one ALPN ("rtp-quic") now and maybe later add one or more ALPNs for multiplexing RTP/RTCP and some other (data) protocols on top of QUIC. We could then also define the actual multiplexing similar to RFC 7983.

I don't think we want to assign an ALPN now that allows multiplexing RTP/RTCP and any other unspecified protocol in the future because it would be unclear how to do the multiplexing.

**Comment by mengelbart** [comment]
#54 solves the multiplexing issue using flow identifiers, which works with the ALPN currently defined in the document.
