### ISSUE TITLE
Add any other relevant details about what QUIC feedback can replace AVP/AVPF feedback

### ISSUE THREAD

**Issue by SpencerDawkins** [mengelbart/rtp-over-quic-draft#48]
This probably has impacts on SDP, depending on whether one QUIC/RTP endpoint needs to tell the other QUIC/RTP endpoint what feedback to send.

**Comment by aboba** [comment]
RTCP messages to consider include messages defined in RFCs 4585, 5104, 8888 and draft-ietf-avtcore-rtcp-green-metadata.

**Comment by mengelbart** [comment]
I think 4585, 5104, and 8888 should all be included now, and I created a new issue to track draft-ietf-avtcore-rtcp-green-metadata: #79
