### ISSUE TITLE
Possible use of QUIC Multicast? 

### ISSUE THREAD

**Issue by SpencerDawkins** [mengelbart/rtp-over-quic-draft#52]
QUIC does not have a [Multicast Extension for QUIC](https://datatracker.ietf.org/doc/draft-jholland-quic-multicast/) on its plate - this is currently an individual draft. 

If $SOMEONE could move this draft forward in QUIC, and $SOMEONE could take on working through the details in AVTCORE, we could provide a QUIC-RTP that could support many of the [RFC 7667](https://datatracker.ietf.org/doc/rfc7667/) topologies that are currently out of scope for us. 

No need for immediate attention to this issue, but it is something to keep in mind, until we decide that it's not.

**Comment by aboba** [comment]
There are no plans to support multicast in WebTransport, so I think we can rule that out. 

Are there any implementations of multicast over raw QUIC?

**Comment by mengelbart** [comment]
We haven't discussed this explicitly, but I think we agree that multicast is not something that needs to be addressed in this version of RoQ. It would add a new dependency to an individual draft which contradicts #127, so I suggest we close this as *won't fix*.

**Comment by SpencerDawkins** [comment]
@SpencerDawkins agrees with @mengelbart on closing this issue within the current RoQ draft work. If we do move forward on this, it should definitely be in another ("follow-on") document, anyway.
