### ISSUE TITLE
Catch up on acknowledgements to date

### ISSUE THREAD

**Issue by SpencerDawkins** [mengelbart/rtp-over-quic-draft#55]
@mengelbart, I added Vidhi Goel when I was working through her review comments (#53), and (I hope this is OK) alphabetized the names that were already included so we can avoid omissions and duplications as we get more (and more) reviews and comments, but it will be good for you and @joerg-ott to make sure we have everyone who has helped so far.

**Comment by mengelbart** [comment]
Alphabetized sounds good. I have more additions, but I will wait for your PR so we don't create unnecessary merge conflicts.
