### ISSUE TITLE
CC/RA: More clearly define what we mean by "QUIC CC", real-time media rate adaptation, etc. in this document.

### ISSUE THREAD

**Issue by SpencerDawkins** [mengelbart/rtp-over-quic-draft#70]
Suggested by @mengelbart in a #62 [comment](https://github.com/mengelbart/rtp-over-quic-draft/issues/62#issuecomment-1462480865).

**Comment by SpencerDawkins** [comment]
@mengelbart - thanks for this proposed text. I have two suggestions, which I'll put in my PR, but what you said was super helpful. 

> Loss-based congestion control algorithm: A congestion control algorithm that uses packet loss as a signal for congestion. Loss-based congestion control algorithms allow senders to send data on a path until packets are dropped by intermediary network elements, which the algorithm treats as a signal of congestion.

I'm being pedantic, but I would also include networks that provide ECN, which is typically treated as data loss (although Scalable Congestion Controllers treat ECN(1) differently

And, actually I'd also include networks that support ECN(1) under "Delay-based or Low-latency congestion control algorithm". So, I guess that's two and a half suggestions? 

> RTP congestion controller: A software component of an RTP implementation that implements a congestion control algorithm.

I THINK that this can also happen in an application using an RTP implementation, can't it?

**Comment by mengelbart** [comment]
Including ECN sounds good to me. Do you suggest including them under loss-based, delay-based, or both?

> I THINK that this can also happen in an application using an RTP implementation, can't it?

Yes, I think this is possible, but maybe it just depends on where you draw the line between the RTP implementation and the application?

**Comment by SpencerDawkins** [comment]
> > I THINK that this can also happen in an application using an RTP implementation, can't it?
> 
> Yes, I think this is possible, but maybe it just depends on where you draw the line between the RTP implementation and the application?

@mengelbart - on thinking more (and more clearly), I don't think we need to address this here.
