### ISSUE TITLE
PLEASE choose an acronym for "RTP over QUIC"!!!

### ISSUE THREAD

**Issue by SpencerDawkins** [mengelbart/rtp-over-quic-draft#74]
If we had a reasonable acronym for "RTP-over-QUIC", our specification would be more than a little bit easier to read. 

I'm not suggesting one - I think @mengelbart and @joerg-ott should have the honor of painting that bikeshed - but I think we need one badly, and I expect marketing types outside the IETF, or even participants in other SDOs, to pick one if we don't. 

:upside_down_face:

**Comment by samhurst** [comment]
Might I suggest [QRT](https://datatracker.ietf.org/doc/html/draft-hurst-quic-rtp-tunnelling)? 😇

Alternatively, maybe just "rq", in the same way that HTTP-over-QUIC was originally "hq"?

**Comment by LPardue** [comment]
The obvious one is one syllable - RoQ. Why not?

**Comment by aboba** [comment]
RoQ - I like it!

**Comment by mengelbart** [comment]
I think RoQ makes sense as it also aligns with MoQ and DoQ. I also just talked to @joerg-ott and we agreed on using RoQ.  I'll open a PR.
