### ISSUE TITLE
Improve consideration for multi-hop topologies

### ISSUE THREAD

**Issue by gloinul** [mengelbart/rtp-over-quic-draft#75]
So the QUIC connection carrying RTP will for now be point to point. However, as RTP has notion of RTP middleboxes that are used to create multiparty topologies there need to be better consideration for when one can do optimizations like reducing the rate of RTCP because the RTCP receiver related statistics will be known by QUIC sender. So if one can reduce the rate or even skip some RTCP reports is all dependent if the RTP middlebox that interconnects has full autonomy and can act on all aspects on the transport feedback. However, if the original sender in a system would monitor all receivers and actually adapt its general rates in a simulcast for example and the middlebox just selects between the simulcast versions then one would have to maintain RTCP reports that does cross reporting over the whole RTP session. 

So I think you need to clarify for example in Section 6.1 that the system needs to decided on its need and use signalling to both configure the reports the system needs as well as the frequency of the RTCP reporting.

**Comment by gloinul** [comment]
I would also note that if a RTP session member does not send any RTCP receiver reports it might be classify it as not longer part of the session. RFC 3550 does only require one to send RTP/RTCP packets the last 5 reporting interval. However, I have feeling that many implementation will us SR or RR as equivalent to sending RTCP as they have been the base line.

**Comment by SpencerDawkins** [comment]
Related to #117
