### ISSUE TITLE
Important: define error codes

### ISSUE THREAD

**Issue by LPardue** [mengelbart/rtp-over-quic-draft#76]
Related to #13 but also applicable to the rest of the specification.

RTP over QUIC is an application layer mapping for RTP applications. 

When using STOP_SENDING or RESET_STREAM, the code has to be an application-layer error code, and you don't have one. Without that, people will just pick random numbers (or worse, send 0 for everything). 

Defining codes isn't too hard, we should put some thought into gradeful or abrupt conditions that can be communicated via error codes

**Comment by SpencerDawkins** [comment]
@LPardue - do you plan to provide text for this issue by the next AVTCORE interim?
