### ISSUE TITLE
Add motivations for RoQ adoption

### ISSUE THREAD

**Issue by SpencerDawkins** [mengelbart/rtp-over-quic-draft#77]
Add motivations for RQ work and adoption

Transport-level encryption with RQ.

Using QUIC as it evolves (connection migration, and especially multipath QUIC).

Thinking about policy aspects of connection migration between interfaces (cheap WiFi vs expensive cellular).

Potential connection sharing with other protocols over QUIC.

QUIC path MTU discovery, especially in multiparty environments (today conference server has no option except using the lowest path MTU for all conference participants). 

ACK piggybacking in QUIC if there are any QUIC frames going the other direction versus ACKs decreasing the available MTU for media. 

Being clear about how RQ congestion control and flow control work.

Possible advantage if audio is piggybacking on video in RQ - packaging multiple frames into a packet. 

Think about how multiple media quality variants would work - is there an advantage here?

Multiplexing real-time and non-real-time flows. 

Interaction between QUIC congestion control and media congestion control.

**Comment by SpencerDawkins** [comment]
Updated motivations issues 

m-Transport-level encryption with RQ.

m-Using QUIC as it evolves (connection migration, and especially multipath QUIC).

m-Potential connection sharing with other protocols over QUIC.

m-QUIC path MTU discovery, especially in multiparty environments (today conference server has no option except using the lowest path MTU for all conference participants).

m-ACK piggybacking in QUIC if there are any QUIC frames going the other direction versus ACKs decreasing the available MTU for media. #85 

m-Possible advantage if audio is piggybacking on video in RQ - packaging multiple frames into a packet.

m-Multiplexing real-time and non-real-time flows.

**Comment by mengelbart** [comment]
These are from discussing with @gchandok

**Comment by SpencerDawkins** [comment]
@SpencerDawkins requested this one be assigned to him, because he is likely responsible for similar text in the [MOQ Requirements draft](https://github.com/moq-wg/moq-requirements).
