### ISSUE TITLE
Add more detail to section 7.3 on congestion control when sharing connections with non-RTP streams

### ISSUE THREAD

**Issue by mengelbart** [mengelbart/rtp-over-quic-draft#84]
[Section 5.1](https://datatracker.ietf.org/doc/html/draft-ietf-avtcore-rtp-over-quic#section-5.1) explains in detail how multiplexing RTP with other protocols would work and [section 7.3](https://datatracker.ietf.org/doc/html/draft-ietf-avtcore-rtp-over-quic#section-7.3) is supposed to explain how to do congestion control for that. But the only sentence about this is rather vague:

> Applications multiplexing multiple streams in one connection SHOULD implement some form of stream prioritization or bandwidth allocation.

This also came up in discussion with Gurtej and is slightly related to the discussion we had here: https://github.com/mengelbart/rtp-over-quic-draft/pull/83#discussion_r1191585178

**Comment by SpencerDawkins** [comment]
We need informed opinions about the maturity of NADA/SCReAM with congestion controllers like BBR - probably a good question for CCWG (former [CONGRESS](https://datatracker.ietf.org/doc/charter-ietf-congress/)) when they are chartered.

**Comment by pthatcher** [comment]
Oen could, of course, just let the QUIC and non-QUIC do their own congestion control that compete with one another.  That's how SCTP and RTP work together in WebRTC.   One could theoretically have the two protocols coordinate with one congestion controller, but that's complex enough work that no one (that I know of) has attempted it.  

I would suggest just leaving this an implementation detail.   If implementations want to try and do the complex work of coordinating the congestion control across different protocols, they can.  If they want to keep it simple and let them compete, they can.

**Comment by SpencerDawkins** [comment]
> Oen could, of course, just let the QUIC and non-QUIC do their own congestion control that compete with one another. That's how SCTP and RTP work together in WebRTC. One could theoretically have the two protocols coordinate with one congestion controller, but that's complex enough work that no one (that I know of) has attempted it.
> 
> I would suggest just leaving this an implementation detail. If implementations want to try and do the complex work of coordinating the congestion control across different protocols, they can. If they want to keep it simple and let them compete, they can.

@pthatcher - I agree, and that seems like helpful guidance that isn't going to be **too** helpful. :laughing:
