### ISSUE TITLE
Coalescing RTP packets in single QUIC packet

### ISSUE THREAD

**Issue by mengelbart** [mengelbart/rtp-over-quic-draft#86]
Over UDP, every RTP packet gets sent in a UDP datagram. In QUIC, one could batch multiple small RTP packets together in a QUIC packet. This will probably happen automatically for streams but may depend on some scheduling for datagrams. That scheduling should take real-time requirements into account, i.e., try to optimize by batching, but also not delay packets too much.

Maybe relevant: https://www.rfc-editor.org/rfc/rfc9000#section-13

**Comment by SpencerDawkins** [comment]
Batching RTP packets is something that QUIC implementations can do, and @mengelbart and @SpencerDawkins think this is worth noting in the document, but it seems more useful to wait until we have some experience that tells us whether this will matter (assuming a conforming QUIC implementation) before we add text about recommendations implementers of RTP senders should consider. .
